export const i18nStrings = {
    'zh-TW': {
        score: "分數",
        time: "時間",
        fever: "應援力量",
        // ✨ 新增 (設定選單)
        settingsTitle: "設定",
        languageSettings: "語言設定",
        otherOptions: "其他選項",
        backButton: "返回",
        // 開始彈窗
        modalStartTitle: "小媛寶生日應援！",
        modalStartText: "接住媛媛喜歡的東西，為她累積應援力量吧！",
        modalStartButton: "開始遊戲",
        // 結束彈窗
        modalEndTitle: "遊戲結束！",
        modalEndText: "您為媛媛累積了 {score} 分應援！", // {score} 會被程式替換
        modalRestartButton: "重新開始",
        modalQuestionTitle: "應援小問答！",
        // ✨ 新增 (結算畫面)
        statsTitle: "本次應援成果",
        statsPositive: "接到物品",
        statsNegative: "接到障礙物",
        statsCorrect: "答對問題",
        statsWrong: "答錯問題",
        shareButton: "分享成果",
        shareText: "我剛剛在媛媛的生日應援遊戲中獲得了 {score} 分，趕快一起來累積應援分數吧！ #HappyYuanDay",
        copiedText: "已複製！",

        // ✨ 新增 (生日彩蛋)
        birthdayTitle: "🎂 Happy Birthday 🎂",
        birthdayMessage: "今天是 1 月 5 日，是媛媛的生日！\n感謝你今天也來為她應援，祝你有個美好的一天！",
        birthdayCloseButton: "關閉",
        // ✨ 新增 (進度ID轉移)
        transferTitle: "進度 ID",
        copyButton: "複製",
        copiedButton: "已複製!",
        importButton: "匯入進度",
        importPlaceholder: "貼上您的進度 ID",
        importConfirm: "確認匯入？這將覆蓋本機遊戲進度！",
        importSuccess: "匯入成功！遊戲將重新載入。",
        importError: "ID 格式無效，請貼上完整的進度 ID。",
        importUITitle: "匯入進度",
        importUIText: "請貼上你的進度 ID 同步更新進度",
        importCancelButton: "取消",
        // ✨ 新增 (個人里程碑)
        milestoneButton: "個人里程碑",
        milestoneTitle: "個人里程碑",
        milestoneDesc: "達成目標累積積分，即可獲得小獎品與大獎的抽獎機會！",
        milestoneClaimButton: "領取獎勵",
        milestoneConfirmButton: "確認",
        milestoneTier1: "數位小卡",
        milestoneTier2: "抽獎資格",
        milestoneTier3: "月曆卡抽獎",
        milestoneQualified: "已獲得資格",
        milestoneDownload: "下載獎勵",
        // ✨ 新增 (全體里程碑 與 流程控制)
        globalMilestoneButton: "全體里程碑",
        globalMilestoneTitle: "全體應援進度",
        globalMilestoneDesc: "這是所有玩家共同累積的應援力量！",
        continueButton: "繼續",
        closeButton: "關閉",
        // ✨ 修正：分享文案模板
        shareTextTemplate: "🌟 應援結果出爐！我在【媛媛生日應援小遊戲】中，本局為媛媛累積了 {score} 分！🎉\n\n累計至今，我已貢獻了 {cumulativeScore} 總應援分！一起衝向全球應援目標 {globalProgress} 吧！\n\n👉 來挑戰最高分：[遊戲連結]\n#2026happyyuanday #幻藍小熊 #GENBLUE",
        shareSuccess: "分享文案已複製到剪貼簿！",
        shareFailure: "複製失敗，請手動複製！",
        loadingTitle: "載入中...",
        // ✨ 新增 (IG 抽獎)
        igPromptTitle: "登錄抽獎資訊",
        igPromptText: "為了讓主辦方能聯繫到您，請留下您的 IG 帳號作為抽獎憑證。",
        igPromptPlaceholder: "請輸入您的 IG 帳號",
        igSubmitButton: "提交",
        igCancelButton: "取消",
        igSaveSuccess: "儲存成功！祝您中獎！",
        igSaveError: "儲存失敗，請檢查網路連線後再試。",
        igAlreadyEntered: "您已使用 @{handle} 參與抽獎。點擊可修改。",
        igEmptyInputError: "請輸入您的 IG 帳號！",
        // ✨ 新增 (垂直里程碑)
        milestoneYourScore: "你的總積分",
        milestoneTier1Title: "第一階段：10,000分",
        milestoneTier1Desc: "獎勵：數位小卡",
        milestoneTier2Title: "第二階段：25,000分",
        milestoneTier2Desc: "獎勵：實體抽獎資格",
        milestoneTier3Title: "第三階段：50,000分",
        milestoneTier3Desc: "獎勵：限定月曆卡抽獎",
        milestoneIgLabel: "IG 帳號：",
        milestoneIgEditButton: "修改",
        tier3ClaimSuccess: "抽獎順利！您已獲得限定月曆卡抽獎資格，請等待活動結束後的官方公告。",
        shareTipStory: "✨ 已選擇限時動態格式 (9:16)，最適合 IG 限動分享",
        shareTipSquare: "✨ 已選擇方形格式 (1:1)，適合所有平台",
        // Offline Syncing
        offlineScoreSaved: "目前為離線狀態，您的分數已暫存，將在恢復連線後自動上傳。",
        offlineScoreError: "抱歉，無法暫存您的離線分數，請檢查瀏覽器儲存空間設定。",
        syncError: "同步離線分數時發生錯誤，尚有 {count} 筆紀錄未完成。請保持網路連線，系統將會重試。",
        syncSuccess: "所有離線遊戲紀錄皆已同步成功！",
        // ✨ 新增 (遊戲說明)
        tutorialTitle: "應援指南",
        tutorialDesc: "左右移動小媛寶，接住想要的東西！",
        tutItemPositive: "💖 加分！累積應援力量",
        tutItemSpecial: "✨ 超讚！大量增加應援力",
        tutItemQuestion: "❓ 挑戰！觸發應援問答",
        tutItemNegative: "⚠️ 小心！記得要閃開",
        tutCloseButton: "我知道了！",
        tutDontShowAgain: "不再顯示此說明",
        stillOffline: "網路尚未恢復連線，請稍後再試。",
        // 🎂 生日祝福
        wishButton: "🎂 獻上祝福",
        viewWishesButton: "🎂 檢視祝福",
        wishModalTitle: "🎂 寫下你的祝福",
        wishNicknamePlaceholder: "你的暱稱",
        wishMessagePlaceholder: "寫下對媛媛的生日祝福...",
        wishSubmitButton: "送出祝福 💕",
        wishCancelButton: "取消",
        wishSubmitSuccess: "祝福已送出！謝謝你 💕",
        wishUpdateSuccess: "祝福已更新！💕",
        wishCharCount: "{current} / {max}",
        wishNicknameRequired: "請輸入暱稱！",
        wishMessageRequired: "請輸入祝福內容！",
        wishEditPrompt: "你已經送出過祝福，要修改嗎？",
        wishWallTitle: "🎂 粉絲祝福牆",
        wishWallDesc: "來自所有粉絲的生日祝福",
        wishWallEmpty: "還沒有祝福，成為第一個送上祝福的人吧！",
    },
    'en': {
        score: "Score",
        time: "Time",
        fever: "Fever",
        // ✨ New (Settings Menu)
        settingsTitle: "Settings",
        languageSettings: "Language Settings",
        otherOptions: "Other Options",
        backButton: "Back",
        troubleshoot: "Troubleshoot",
        troubleshootDesc: "If the game is lagging or displaying incorrectly, try repairing it.",
        repairGame: "Repair Game (Clear Cache)",
        // Start Modal
        modalStartTitle: "Yuan's Birthday Support!",
        modalStartText: "Catch items Yuan loves to build up support power!",
        modalStartButton: "Start Game",
        // End Modal
        modalEndTitle: "Game Over!",
        modalEndText: "You earned {score} support points for Yuan!",
        modalRestartButton: "Restart",
        modalQuestionTitle: "Support Quiz!",

        // Stats
        statsTitle: "Support Results",
        statsPositive: "Items Caught",
        statsNegative: "Obstacles Hit",
        statsCorrect: "Quiz Correct",
        statsWrong: "Quiz Wrong",
        shareButton: "Share Score",
        shareText: "I just got {score} points in Yuan's Birthday Support Game! Come join us and collect points! #HappyYuanDay",
        copiedText: "Copied!",

        // Birthday Modal
        birthdayTitle: "🎂 Happy Birthday 🎂",
        birthdayMessage: "Today is January 5th, Yuan's Birthday!\nThank you for supporting her today. Have a wonderful day!",
        birthdayCloseButton: "Close",

        // ID Transfer
        transferTitle: "Progress ID",
        copyButton: "Copy",
        copiedButton: "Copied!",
        importButton: "Import Progress",
        importPlaceholder: "Paste your Progress ID here",
        importConfirm: "Confirm import? This will overwrite local progress!",
        importSuccess: "Import successful! The game will reload.",
        importError: "Invalid ID format. Please paste the full ID.",
        importUITitle: "Import Progress",
        importUIText: "Please paste your Progress ID to sync progress",
        importCancelButton: "Cancel",
        // Personal Milestones
        milestoneButton: "Milestones",
        milestoneTitle: "Personal Milestones",
        milestoneDesc: "Reach score goals to get digital cards and chances to win grand prizes!",
        milestoneClaimButton: "Claim Reward",
        milestoneConfirmButton: "Confirm",
        milestoneTier1: "Digital Card",
        milestoneTier2: "Raffle Entry",
        milestoneTier3: "Calender Raffle",
        milestoneQualified: "Qualified",
        milestoneDownload: "Download Reward",
        // Global Milestones
        globalMilestoneButton: "Global Milestone",
        globalMilestoneTitle: "Global Support Progress",
        globalMilestoneDesc: "This is the total support power collected by all players!",
        continueButton: "Continue",
        closeButton: "Close",
        // Share Text
        shareTextTemplate: "🌟 Result out! I scored {score} points for Yuan in the [Yuan's Birthday Support Game]! 🎉\n\nMy total cumulative support score is {cumulativeScore}! Let's hit the Global Milestone of {globalProgress} together!\n\n👉 Challenge me: [Game Link]\n#2026happyyuanday #GENBLUE",
        loadingTitle: "Loading...",
        // IG Raffle
        igPromptTitle: "Raffle Registration",
        igPromptText: "To ensure the organizer can contact you, please provide your IG handle for the raffle.",
        igPromptPlaceholder: "Enter your IG handle",
        igSubmitButton: "Submit",
        igCancelButton: "Cancel",
        igSaveSuccess: "Saved successfully! Good luck in the draw!",
        igSaveError: "Save failed. Please check your connection and try again.",
        igAlreadyEntered: "You have already entered the raffle with @{handle}. Click to edit.",
        igEmptyInputError: "Please enter your IG handle!",
        // Vertical Milestones
        milestoneYourScore: "Your Total Score",
        milestoneTier1Title: "Tier 1: 10,000 Points",
        milestoneTier1Desc: "Reward: Digital Photocard",
        milestoneTier2Title: "Tier 2: 25,000 Points",
        milestoneTier2Desc: "Reward: Raffle Entry",
        milestoneTier3Title: "Tier 3: 50,000 Points",
        milestoneTier3Desc: "Reward: Limited Calendar Card Raffle",
        milestoneIgLabel: "IG Handle:",
        milestoneIgEditButton: "Edit",
        tier3ClaimSuccess: "Raffle entry successful! You have qualified for the Limited Calendar Card Raffle. Please wait for the official announcement after the event ends.",
        shareTipStory: "✨ Story format (9:16) selected, best for IG Stories.",
        shareTipSquare: "✨ Square format (1:1) selected, suitable for all platforms.",
        // Offline Syncing
        offlineScoreSaved: "You are currently offline. Your score has been saved locally and will be uploaded automatically when you reconnect.",
        offlineScoreError: "Sorry, your offline score could not be saved. Please check your browser storage settings.",
        syncError: "An error occurred while syncing offline scores. {count} records remain unsynced. Please maintain your connection, and the system will retry.",
        syncSuccess: "All offline game records have been successfully synced!",
        stillOffline: "Still offline. Please try again later.",
        // ✨ New (Tutorial)
        tutorialTitle: "How to Play",
        tutorialDesc: "Move left/right to catch items!",
        tutItemPositive: "💖 Score Up & Build Fever",
        tutItemSpecial: "✨ Big Bonus & Boost Fever",
        tutItemQuestion: "❓ Challenge! Trigger Quiz",
        tutItemNegative: "⚠️ Watch out! Avoid these",
        tutCloseButton: "Got it!",
        tutDontShowAgain: "Don't show this again",
        // 🎂 Birthday Wishes
        wishButton: "🎂 Send Wishes",
        viewWishesButton: "🎂 View Wishes",
        wishModalTitle: "🎂 Write Your Wishes",
        wishNicknamePlaceholder: "Your Nickname",
        wishMessagePlaceholder: "Write your birthday wishes for Yuan...",
        wishSubmitButton: "Send Wishes 💕",
        wishCancelButton: "Cancel",
        wishSubmitSuccess: "Wishes sent! Thank you 💕",
        wishUpdateSuccess: "Wishes updated! 💕",
        wishCharCount: "{current} / {max}",
        wishNicknameRequired: "Please enter your nickname!",
        wishMessageRequired: "Please enter your wishes!",
        wishEditPrompt: "You've already sent wishes. Do you want to edit?",
        wishWallTitle: "🎂 Fan Wishes Wall",
        wishWallDesc: "Birthday wishes from all fans",
        wishWallEmpty: "No wishes yet. Be the first to send your wishes!",
    }
};